
window.athletesData = 
[

            {
                id: 1,
                name: "Кузнецов Сергей",
                region: "Чувашская Республика - Чувашия",
                gender: "m",
                birthYear: 1992,
                rank: "МС",
                rankText: "Мастер спорта",
                link: "pers_1.html",
            },
            {
                id: 2,
                name: "Байкенов Ерлан",
                region: "Свердловская область",
                gender: "m",
                birthYear: 1992,
                rank: "МС",
                rankText: "Мастер спорта",
                link: "pers_2.html",
            },
            {
                id: 3,
                name: "Колесов Павел",
                region: "Самарская область",
                gender: "m",
                birthYear: 2003,
                rank: "КМС",
                rankText: "Кандидат в мастера спорта",
                link: "pers_3.html",
            },
            {
                id: 4,
                name: "Безносиков Владислав",
                region: "Республика Коми",
                gender: "m",
                birthYear: 1996,
                rank: "МС",
                rankText: "Мастер спорта",
                link: "pers_4.html",
            },
            {
                id: 5,
                name: "Михеев Василий",
                region: "Челябинская область",
                gender: "m",
                birthYear: 2003,
                rank: "МС",
                rankText: "Мастер спорта",
                link: "pers_5.html",
            },
            {
                id: 6,
                name: "Дмитриев Георгий",
                region: "Республика Марий Эл",
                gender: "m",
                birthYear: 2002,
                rank: "МС",
                rankText: "Мастер спорта",
                link: "pers_6.html",
            },
            {
                id: 7,
                name: "Ющик Никита",
                region: "Белгородская область",
                gender: "m",
                birthYear: 2000,
                rank: "МС",
                rankText: "Мастер спорта",
                link: "pers_7.html",
            },
            {
                id: 8,
                name: "Урдяков Рустам",
                region: "Республика Марий Эл",
                gender: "m",
                birthYear: 1998,
                rank: "МС",
                rankText: "Мастер спорта",
                link: "pers_8.html",
            },
            {
                id: 9,
                name: "Львов Андрей",
                region: "Чувашская Республика - Чувашия",
                gender: "m",
                birthYear: 1988,
                rank: "МС",
                rankText: "Мастер спорта",
                link: "pers_9.html",
            },
            {
                id: 10,
                name: "Мудрак Никита",
                region: "город Севастополь",
                gender: "m",
                birthYear: 2002,
                rank: "КМС",
                rankText: "Кандидат в мастера спорта",
                link: "pers_10.html",
            },
            {
                id: 11,
                name: "Кудряшов Александр",
                region: "Белгородская область",
                gender: "m",
                birthYear: 1989,
                rank: "МС",
                rankText: "Мастер спорта",
                link: "pers_11.html",
            },
            {
                id: 12,
                name: "Рожков Константин",
                region: "Республика Марий Эл",
                gender: "m",
                birthYear: 2003,
                rank: "МС",
                rankText: "Мастер спорта",
                link: "pers_12.html",
            },
            {
                id: 13,
                name: "Ушаков Савелий",
                region: "Республика Коми",
                gender: "m",
                birthYear: 2003,
                rank: "МС",
                rankText: "Мастер спорта",
                link: "pers_13.html",
            },
            {
                id: 14,
                name: "Жильцов Алексей",
                region: "Белгородская область",
                gender: "m",
                birthYear: 1979,
                rank: "МС",
                rankText: "Мастер спорта",
                link: "pers_14.html",
            },
            {
                id: 15,
                name: "Прокопьев Андрей",
                region: "Чувашская Республика - Чувашия",
                gender: "m",
                birthYear: 2003,
                rank: "КМС",
                rankText: "Кандидат в мастера спорта",
                link: "pers_15.html",
            },
            {
                id: 16,
                name: "Тельбух Иван",
                region: "Московская область",
                gender: "m",
                birthYear: 2005,
                rank: "КМС",
                rankText: "Кандидат в мастера спорта",
                link: "pers_16.html",
            },
            {
                id: 17,
                name: "Калиновский Леонид",
                region: "Московская область",
                gender: "m",
                birthYear: 1995,
                rank: "МС",
                rankText: "Мастер спорта",
                link: "pers_17.html",
            },
            {
                id: 18,
                name: "Тюрин Денис",
                region: "Московская область",
                gender: "m",
                birthYear: 1999,
                rank: "КМС",
                rankText: "Кандидат в мастера спорта",
                link: "pers_18.html",
            },
            {
                id: 19,
                name: "Пешиков Сергей",
                region: "Московская область",
                gender: "m",
                birthYear: 1990,
                rank: "МС",
                rankText: "Мастер спорта",
                link: "pers_19.html",
            }
];